### ISSUE TITLE
Timer not Proper Showing

### ISSUE THREAD

**Issue by Biplovkumar** [talalmajali/react-native-countdown-component#13]
only one digit is showing in minutes and second.
![screenshot_20180916-210353](https://user-images.githubusercontent.com/30401136/45625269-15568b00-baaa-11e8-8446-468a7b041e3b.jpg)

**Comment by talalmajali** [comment]
@Biplovkumar What is the model of the device?

**Comment by Biplovkumar** [comment]
Android device One plus 5t Android

**Comment by Biplovkumar** [comment]
Any update  ?

**Comment by talalmajali** [comment]
@Biplovkumar is this happening on a specific countdown component size?
What's the size that are you using here? 
and can you make sure that the device font size (in settings) is set to default?

**Comment by talalmajali** [comment]
@Biplovkumar i ran the same code on same device (1080 x 2160 pixels) screen OnePlus 5T
and it's showing without any problems, it's not screen scaling problem, i think what u meant to say that the minutes and seconds should have leading zero before each of them, so in the image the timer should be rendered as 01 05, right?

**Comment by samybenatt** [comment]
Hi,

This problem is common on OnePlus phones and related to **React Native**.
Here is the RN issue :  https://github.com/facebook/react-native/issues/15114

Common fixes for this issue : 

- Change text font and/or app font
- Give the text component containing the cut offed text a custom width
- Add a space just after the text cut offed

You have all the other possible solutions on the link above.

Tested on my device and it worked !

**Comment by Biplovkumar** [comment]
@samay
